//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
// 
#pragma warning disable 1591

namespace Flight_Server.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="FlightsServiceSoap", Namespace="http://flights.com/")]
    public partial class FlightsService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BuyTicketOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllFlightsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetArrivalCitiesByDepartureOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCustomerFlightsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateCustomerOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFlightsCitiesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFlightPriceOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public FlightsService() {
            this.Url = global::Flight_Server.Properties.Settings.Default.Flight_Server_localhost_FlightsService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BuyTicketCompletedEventHandler BuyTicketCompleted;
        
        /// <remarks/>
        public event GetAllFlightsCompletedEventHandler GetAllFlightsCompleted;
        
        /// <remarks/>
        public event GetArrivalCitiesByDepartureCompletedEventHandler GetArrivalCitiesByDepartureCompleted;
        
        /// <remarks/>
        public event AddCustomerCompletedEventHandler AddCustomerCompleted;
        
        /// <remarks/>
        public event GetCustomersCompletedEventHandler GetCustomersCompleted;
        
        /// <remarks/>
        public event GetCustomerFlightsCompletedEventHandler GetCustomerFlightsCompleted;
        
        /// <remarks/>
        public event UpdateCustomerCompletedEventHandler UpdateCustomerCompleted;
        
        /// <remarks/>
        public event GetFlightsCitiesCompletedEventHandler GetFlightsCitiesCompleted;
        
        /// <remarks/>
        public event GetFlightPriceCompletedEventHandler GetFlightPriceCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://flights.com/BuyTicket", RequestNamespace="http://flights.com/", ResponseNamespace="http://flights.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BuyTicket(string departure, string arrival, string name, string surname) {
            this.Invoke("BuyTicket", new object[] {
                        departure,
                        arrival,
                        name,
                        surname});
        }
        
        /// <remarks/>
        public void BuyTicketAsync(string departure, string arrival, string name, string surname) {
            this.BuyTicketAsync(departure, arrival, name, surname, null);
        }
        
        /// <remarks/>
        public void BuyTicketAsync(string departure, string arrival, string name, string surname, object userState) {
            if ((this.BuyTicketOperationCompleted == null)) {
                this.BuyTicketOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuyTicketOperationCompleted);
            }
            this.InvokeAsync("BuyTicket", new object[] {
                        departure,
                        arrival,
                        name,
                        surname}, this.BuyTicketOperationCompleted, userState);
        }
        
        private void OnBuyTicketOperationCompleted(object arg) {
            if ((this.BuyTicketCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuyTicketCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://flights.com/GetAllFlights", RequestNamespace="http://flights.com/", ResponseNamespace="http://flights.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetAllFlights() {
            object[] results = this.Invoke("GetAllFlights", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetAllFlightsAsync() {
            this.GetAllFlightsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllFlightsAsync(object userState) {
            if ((this.GetAllFlightsOperationCompleted == null)) {
                this.GetAllFlightsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllFlightsOperationCompleted);
            }
            this.InvokeAsync("GetAllFlights", new object[0], this.GetAllFlightsOperationCompleted, userState);
        }
        
        private void OnGetAllFlightsOperationCompleted(object arg) {
            if ((this.GetAllFlightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllFlightsCompleted(this, new GetAllFlightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://flights.com/GetArrivalCitiesByDeparture", RequestNamespace="http://flights.com/", ResponseNamespace="http://flights.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetArrivalCitiesByDeparture(string departure) {
            object[] results = this.Invoke("GetArrivalCitiesByDeparture", new object[] {
                        departure});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetArrivalCitiesByDepartureAsync(string departure) {
            this.GetArrivalCitiesByDepartureAsync(departure, null);
        }
        
        /// <remarks/>
        public void GetArrivalCitiesByDepartureAsync(string departure, object userState) {
            if ((this.GetArrivalCitiesByDepartureOperationCompleted == null)) {
                this.GetArrivalCitiesByDepartureOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetArrivalCitiesByDepartureOperationCompleted);
            }
            this.InvokeAsync("GetArrivalCitiesByDeparture", new object[] {
                        departure}, this.GetArrivalCitiesByDepartureOperationCompleted, userState);
        }
        
        private void OnGetArrivalCitiesByDepartureOperationCompleted(object arg) {
            if ((this.GetArrivalCitiesByDepartureCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetArrivalCitiesByDepartureCompleted(this, new GetArrivalCitiesByDepartureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://flights.com/AddCustomer", RequestNamespace="http://flights.com/", ResponseNamespace="http://flights.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddCustomer(string name, string surname) {
            this.Invoke("AddCustomer", new object[] {
                        name,
                        surname});
        }
        
        /// <remarks/>
        public void AddCustomerAsync(string name, string surname) {
            this.AddCustomerAsync(name, surname, null);
        }
        
        /// <remarks/>
        public void AddCustomerAsync(string name, string surname, object userState) {
            if ((this.AddCustomerOperationCompleted == null)) {
                this.AddCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddCustomerOperationCompleted);
            }
            this.InvokeAsync("AddCustomer", new object[] {
                        name,
                        surname}, this.AddCustomerOperationCompleted, userState);
        }
        
        private void OnAddCustomerOperationCompleted(object arg) {
            if ((this.AddCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://flights.com/GetCustomers", RequestNamespace="http://flights.com/", ResponseNamespace="http://flights.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCustomers() {
            object[] results = this.Invoke("GetCustomers", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomersAsync() {
            this.GetCustomersAsync(null);
        }
        
        /// <remarks/>
        public void GetCustomersAsync(object userState) {
            if ((this.GetCustomersOperationCompleted == null)) {
                this.GetCustomersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomersOperationCompleted);
            }
            this.InvokeAsync("GetCustomers", new object[0], this.GetCustomersOperationCompleted, userState);
        }
        
        private void OnGetCustomersOperationCompleted(object arg) {
            if ((this.GetCustomersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomersCompleted(this, new GetCustomersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://flights.com/GetCustomerFlights", RequestNamespace="http://flights.com/", ResponseNamespace="http://flights.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetCustomerFlights(int customerId) {
            object[] results = this.Invoke("GetCustomerFlights", new object[] {
                        customerId});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetCustomerFlightsAsync(int customerId) {
            this.GetCustomerFlightsAsync(customerId, null);
        }
        
        /// <remarks/>
        public void GetCustomerFlightsAsync(int customerId, object userState) {
            if ((this.GetCustomerFlightsOperationCompleted == null)) {
                this.GetCustomerFlightsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCustomerFlightsOperationCompleted);
            }
            this.InvokeAsync("GetCustomerFlights", new object[] {
                        customerId}, this.GetCustomerFlightsOperationCompleted, userState);
        }
        
        private void OnGetCustomerFlightsOperationCompleted(object arg) {
            if ((this.GetCustomerFlightsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCustomerFlightsCompleted(this, new GetCustomerFlightsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://flights.com/UpdateCustomer", RequestNamespace="http://flights.com/", ResponseNamespace="http://flights.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateCustomer(string name, string surname) {
            this.Invoke("UpdateCustomer", new object[] {
                        name,
                        surname});
        }
        
        /// <remarks/>
        public void UpdateCustomerAsync(string name, string surname) {
            this.UpdateCustomerAsync(name, surname, null);
        }
        
        /// <remarks/>
        public void UpdateCustomerAsync(string name, string surname, object userState) {
            if ((this.UpdateCustomerOperationCompleted == null)) {
                this.UpdateCustomerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateCustomerOperationCompleted);
            }
            this.InvokeAsync("UpdateCustomer", new object[] {
                        name,
                        surname}, this.UpdateCustomerOperationCompleted, userState);
        }
        
        private void OnUpdateCustomerOperationCompleted(object arg) {
            if ((this.UpdateCustomerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateCustomerCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://flights.com/GetFlightsCities", RequestNamespace="http://flights.com/", ResponseNamespace="http://flights.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetFlightsCities() {
            object[] results = this.Invoke("GetFlightsCities", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetFlightsCitiesAsync() {
            this.GetFlightsCitiesAsync(null);
        }
        
        /// <remarks/>
        public void GetFlightsCitiesAsync(object userState) {
            if ((this.GetFlightsCitiesOperationCompleted == null)) {
                this.GetFlightsCitiesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFlightsCitiesOperationCompleted);
            }
            this.InvokeAsync("GetFlightsCities", new object[0], this.GetFlightsCitiesOperationCompleted, userState);
        }
        
        private void OnGetFlightsCitiesOperationCompleted(object arg) {
            if ((this.GetFlightsCitiesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFlightsCitiesCompleted(this, new GetFlightsCitiesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://flights.com/GetFlightPrice", RequestNamespace="http://flights.com/", ResponseNamespace="http://flights.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetFlightPrice(string departure, string arrival) {
            object[] results = this.Invoke("GetFlightPrice", new object[] {
                        departure,
                        arrival});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetFlightPriceAsync(string departure, string arrival) {
            this.GetFlightPriceAsync(departure, arrival, null);
        }
        
        /// <remarks/>
        public void GetFlightPriceAsync(string departure, string arrival, object userState) {
            if ((this.GetFlightPriceOperationCompleted == null)) {
                this.GetFlightPriceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFlightPriceOperationCompleted);
            }
            this.InvokeAsync("GetFlightPrice", new object[] {
                        departure,
                        arrival}, this.GetFlightPriceOperationCompleted, userState);
        }
        
        private void OnGetFlightPriceOperationCompleted(object arg) {
            if ((this.GetFlightPriceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFlightPriceCompleted(this, new GetFlightPriceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BuyTicketCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAllFlightsCompletedEventHandler(object sender, GetAllFlightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllFlightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllFlightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetArrivalCitiesByDepartureCompletedEventHandler(object sender, GetArrivalCitiesByDepartureCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetArrivalCitiesByDepartureCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetArrivalCitiesByDepartureCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddCustomerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCustomersCompletedEventHandler(object sender, GetCustomersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetCustomerFlightsCompletedEventHandler(object sender, GetCustomerFlightsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCustomerFlightsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCustomerFlightsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void UpdateCustomerCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetFlightsCitiesCompletedEventHandler(object sender, GetFlightsCitiesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFlightsCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFlightsCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetFlightPriceCompletedEventHandler(object sender, GetFlightPriceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFlightPriceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFlightPriceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591